location_index:
    path:     /location
    defaults: { _controller: "RentBundle:Location:index" }
    methods:  GET

location_show:
    path:    /showRent/{idL}
    defaults: { _controller: "RentBundle:Location:show" }
    methods:  GET

location_new:
    path:     /newRent
    defaults: { _controller: "RentBundle:Location:new" }
    methods:  [GET, POST]

location_edit:
    path:    /editRent/{idL}
    defaults: { _controller: "RentBundle:Location:edit" }
    methods:  [GET, POST]

location_delete:
    path:    /deleteRent/{idL}
    defaults: { _controller: "RentBundle:Location:delete" }
    methods:  DELETE
