adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml" 

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
rent:
    resource: "@RentBundle/Resources/config/routing.yml"
    prefix:   /rent

product:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /produit

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /event

circuit:
    resource: "@CircuitBundle/Resources/config/routing.yml"
    prefix:   /circuit

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog

annonce:
    resource: "@AnnonceBundle/Resources/config/routing.yml"
    prefix:   /annonce

app:
    resource: '@AppBundle/Controller/'
    type: annotation
