mobile_api_homepage:
    path:     /api
    defaults: { _controller: MobileAPIBundle:Default:index }


locations_all:
    path:     /locations/all
    defaults: { _controller: MobileAPIBundle:Location:all}

reservations_all:
    path:     /reservations/all
    defaults: { _controller: MobileAPIBundle:Reservation:all}

locations_find:
    path:     /locations/find/{id}
    defaults: { _controller: MobileAPIBundle:Location:find}

reservations_find:
    path:     /reservations/find/{id}
    defaults: { _controller: MobileAPIBundle:Reservation:find}

location_create:
    path:     /location/new
    defaults: { _controller: MobileAPIBundle:Location:new}

location_update:
    path:     /location/update/{id}
    defaults: { _controller: MobileAPIBundle:Location:update}

location_delete:
    path:     /location/delete/{id}
    defaults: { _controller: MobileAPIBundle:Location:delete}

reservations_create:
    path:     /reservation/new
    defaults: { _controller: MobileAPIBundle:Reservation:new}


reservation_update:
    path:     /reservation/update/{id}
    defaults: { _controller: MobileAPIBundle:Reservation:update}

reservation_delete:
    path:     /reservation/delete/{id}
    defaults: { _controller: MobileAPIBundle:Reservation:delete}