rent_reservation:
    resource: "@RentBundle/Resources/config/routing/reservation.yml"
    prefix:   /reservation

rent_location:
    resource: "@RentBundle/Resources/config/routing/location.yml"
    prefix:   /location

homepage:
    path:     /rent
    defaults: { _controller: RentBundle:Location:home }

admin_homepage:  
    path:     /admin
    defaults: { _controller: RentBundle:Admin:dash }

location_homepage:
    path:     /location
    defaults: { _controller: RentBundle:Location:index }

location_new:
    path:     /newRent
    defaults: { _controller: RentBundle:Location:new }

location_show:
    path:     /showRent{id}
    defaults: { _controller: RentBundle:Location:show }

location_confirmation:
    path:     /confirme
    defaults: { _controller: RentBundle:Location:confirme }

location_edit:
    path:    /editRent{id}
    defaults: { _controller: RentBundle:Location:edit }
  
location_delete:
    path:    /deleteRent/{id}
    defaults: { _controller: "RentBundle:Location:delete" }


location_rech:
    path:    /rech{id}
    defaults: { _controller: RentBundle:Location:recherche }

reservation_index:
    path:     /reservation
    defaults: { _controller: "RentBundle:Reservation:index" }
   
reservation_show:
    path:    /showReserv{id}
    defaults: { _controller: "RentBundle:Reservation:show" }
  

reservation_new:
    path:     /newReserv
    defaults: { _controller: "RentBundle:Reservation:new" }
   

reservation_edit:
    path:     /editReserv{id}
    defaults: { _controller: "RentBundle:Reservation:edit" }
  

reservation_delete:
    path:     /deleteReserv/{id}
    defaults: { _controller: "RentBundle:Reservation:delete" }
  
reservation_notif:  
    path:     /notif/{id}
    defaults: { _controller: "RentBundle:Reservation:notif" }