rent_reservation:
    resource: "@RentBundle/Resources/config/routing/reservation.yml"
    prefix:   /reservation

rent_location:
    resource: "@RentBundle/Resources/config/routing/location.yml"
    prefix:   /location

homepage:
    path:     /
    defaults: { _controller: RentBundle:location:home }

rent_homepage:
    path:     /location
    defaults: { _controller: RentBundle:location:index }

location_new:
    path:     /newRent
    defaults: { _controller: RentBundle:Location:new }

location_show:
    path:     /showRent{id}
    defaults: { _controller: RentBundle:Location:show }

location_confirmation:
    path:     /confirme
    defaults: { _controller: RentBundle:Location:confirme }

location_edit:
    path:    /editRent{id}
    defaults: { _controller: RentBundle:Location:edit }
    methods:  [GET, POST]

location_rech:
    path:    /rech{id}
    defaults: { _controller: RentBundle:Location:recherche }
       